require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'iplayya' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # react-native-image-picker
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # googlecast guest mode
  pod 'react-native-google-cast/GuestMode', path: '../node_modules/react-native-google-cast/ios/'
  pod 'google-cast-sdk'

  target 'iplayyaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'iplayya-tvOS' do
  # Pods for iplayya-tvOS

  target 'iplayya-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
